version: '3.8'

services:
  envoy:
    image: envoyproxy/envoy:v1.31-latest
    container_name: envoy-gateway
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_BIND_SERVICE
    volumes:
      - ./config/envoy.yaml:/etc/envoy/envoy.yaml:ro
      - ./logs:/var/log/envoy
    command: ["-c", "/etc/envoy/envoy.yaml", "--log-level", "info"]
