services:
  user-service:
    image: registry.gitlab.com/shubhamsinghhrx/user-service:v1.0.29
    env_file: .env
    ports:
      - "7501:7501"
    restart: always

  shikshaspace-service:
    image: registry.gitlab.com/shubhamsinghhrx/shikshaspace-service:v1.0.24
    env_file: .env
    ports:
      - "7502:7502"
    restart: always
