apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "reactive-microservice.fullname" . }}
  labels:
    {{- include "reactive-microservice.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "reactive-microservice.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "reactive-microservice.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.health.livenessProbe | nindent 10 }}
          readinessProbe:
            {{- toYaml .Values.health.readinessProbe | nindent 10 }}
          resources:
            {{- toYaml .Values.resources | nindent 10 }}
          env:
            - name: JAVA_OPTS
              value: "-Xmx256m -Xms128m"
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
