version: '3.8'

services:
  user-service:
    image: registry.gitlab.com/shikshaspace/user-service:${USER_SERVICE_VERSION}
    container_name: user-service
    env_file:
      - ./user-service/.env
    ports:
      - "7501:7501"
    restart: always
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:7501/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 40s

  shikshaspace-service:
    image: registry.gitlab.com/shikshaspace/shikshaspace-service:${SHIKSHASPACE_SERVICE_VERSION}
    container_name: shikshaspace-service
    env_file:
      - ./shikshaspace-service/.env
    ports:
      - "7502:7502"
    restart: always
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:7502/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s

  shikshaspace-ui:
    image: registry.gitlab.com/shikshaspace/shikshaspace-ui:${SHIKSHASPACE_UI_VERSION}
    container_name: shikshaspace-ui
    env_file:
      - ./shikshaspace-ui/.env
    ports:
      - "7500:7500"
    restart: always
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:7500/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 40s
