serviceName: user-service
namespace: prod
replicaCount: 2  # Higher replicas for production

image:
  repository: registry.gitlab.com/shubhamsinghhrx/user-service
  tag: "1.0.2067961336"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 7501

resources:
  requests:
    memory: "256Mi"  # Higher resources for production
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"

healthChecks:
  enabled: true
  livenessPath: "/actuator/health"
  readinessPath: "/actuator/health"
