serviceName: user-service
namespace: prod
replicaCount: 2

image:
  repository: registry.gitlab.com/shubhamsinghhrx/user-service
  tag: latest
  pullPolicy: Always

service:
  type: NodePort
  port: 80
  targetPort: 7501
  nodePort: 30001

# Only add probe settings - env comes from secret
livenessProbe:
  httpGet:
    path: /actuator/health
    port: 7501
  initialDelaySeconds: 120
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /actuator/health
    port: 7501
  initialDelaySeconds: 90
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
