serviceName: shikshaspace-service
namespace: prod
replicaCount: 2

image:
  repository: registry.gitlab.com/shubhamsinghhrx/shikshaspace-service
  tag: "latest"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 7502

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"

healthChecks:
  enabled: true
  livenessPath: "/actuator/health"
  readinessPath: "/actuator/health"
