serviceName: user-service
namespace: prod
replicaCount: 2

image:
  repository: registry.gitlab.com/shubhamsinghhrx/user-service
  tag: latest
  pullPolicy: Always

service:
  type: NodePort
  port: 80
  targetPort: 7501
  nodePort: 30001

# ADD/UPDATE THESE SECTIONS
livenessProbe:
  httpGet:
    path: /actuator/health
    port: 7501
  initialDelaySeconds: 120    # Wait 2 minutes before first check
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /actuator/health
    port: 7501
  initialDelaySeconds: 90     # Wait 90 seconds before first check
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

env:
# ... your existing env section
