apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-service-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.com/shubhamsinghhrx/shikshaspace-infrastructure.git
    targetRevision: HEAD
    path: microservice
    helm:
      valueFiles:
        - ../environments/prod/values-user-service.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shikshaspace-service-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.com/shubhamsinghhrx/shikshaspace-infrastructure.git
    targetRevision: HEAD
    path: microservice
    helm:
      valueFiles:
        - ../environments/prod/values-shikshaspace-service.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
