admin:
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9901

layered_runtime:
  layers:
    - name: static_layer_0
      static_layer:
        overload:
          global_downstream_max_connections: 50000

static_resources:
  listeners:
    - name: http_listener
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 8081
      drain_type: MODIFY_ONLY
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                drain_timeout: 30s
                delayed_close_timeout: 10s
                access_log:
                  - name: envoy.access_loggers.file
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
                      path: /var/log/envoy/access.log
                route_config:
                  name: main_route
                  virtual_hosts:
                    - name: ui_service
                      domains: ["shubhamsinghrajput.com"]
                      routes:
                        - match: {prefix: "/"}
                          route:
                            cluster: ui-cluster
                            timeout: 60s
                            retry_policy:
                              retry_on: "5xx,reset,connect-failure,refused-stream"
                              num_retries: 2

                    - name: user_service
                      domains: ["users.shubhamsinghrajput.com"]
                      routes:
                        - match: {prefix: "/"}
                          route:
                            cluster: user-service-cluster
                            timeout: 30s
                            retry_policy:
                              retry_on: "5xx,reset,connect-failure,refused-stream"
                              num_retries: 2

                    - name: shikshaspace_service
                      domains: ["shikshaspace.shubhamsinghrajput.com"]
                      routes:
                        - match: {prefix: "/"}
                          route:
                            cluster: shikshaspace-service-cluster
                            timeout: 30s
                            retry_policy:
                              retry_on: "5xx,reset,connect-failure,refused-stream"
                              num_retries: 2

                    - name: keycloak
                      domains: ["keycloak.shubhamsinghrajput.com"]
                      routes:
                        - match: {prefix: "/"}
                          route:
                            cluster: keycloak-cluster
                            timeout: 60s

                http_filters:
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

  clusters:
    # UI Cluster - Passive health check only
    - name: ui-cluster
      connect_timeout: 5s
      type: STRICT_DNS
      lb_policy: ROUND_ROBIN
      outlier_detection:
        consecutive_5xx: 5
        consecutive_gateway_failure: 3
        interval: 10s
        base_ejection_time: 30s
        max_ejection_percent: 50
        enforcing_consecutive_5xx: 100
        enforcing_consecutive_gateway_failure: 100
      load_assignment:
        cluster_name: ui-cluster
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 127.0.0.1
                      port_value: 7500
              - endpoint:
                  address:
                    socket_address:
                      address: 127.0.0.1
                      port_value: 7510

    # User Service - Active + Passive health check
    - name: user-service-cluster
      connect_timeout: 5s
      type: STRICT_DNS
      lb_policy: ROUND_ROBIN
      health_checks:
        - timeout: 5s
          interval: 10s
          unhealthy_threshold: 2
          healthy_threshold: 2
          http_health_check:
            path: /actuator/health/readiness
      outlier_detection:
        consecutive_5xx: 5
        consecutive_gateway_failure: 3
        interval: 10s
        base_ejection_time: 30s
        max_ejection_percent: 50
      load_assignment:
        cluster_name: user-service-cluster
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 127.0.0.1
                      port_value: 7501
              - endpoint:
                  address:
                    socket_address:
                      address: 127.0.0.1
                      port_value: 7511

    # ShikshaSpace Service - Active + Passive health check
    - name: shikshaspace-service-cluster
      connect_timeout: 5s
      type: STRICT_DNS
      lb_policy: ROUND_ROBIN
      health_checks:
        - timeout: 5s
          interval: 10s
          unhealthy_threshold: 2
          healthy_threshold: 2
          http_health_check:
            path: /actuator/health/readiness
      outlier_detection:
        consecutive_5xx: 5
        consecutive_gateway_failure: 3
        interval: 10s
        base_ejection_time: 30s
        max_ejection_percent: 50
      load_assignment:
        cluster_name: shikshaspace-service-cluster
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 127.0.0.1
                      port_value: 7502
              - endpoint:
                  address:
                    socket_address:
                      address: 127.0.0.1
                      port_value: 7512

    # Keycloak - Active health check only
    - name: keycloak-cluster
      connect_timeout: 5s
      type: STRICT_DNS
      lb_policy: ROUND_ROBIN
      health_checks:
        - timeout: 5s
          interval: 15s
          unhealthy_threshold: 3
          healthy_threshold: 2
          http_health_check:
            path: /health
      load_assignment:
        cluster_name: keycloak-cluster
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 127.0.0.1
                      port_value: 8080
