admin:
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9901

# Graceful Shutdown Configuration
layered_runtime:
  layers:
    - name: static_layer_0
      static_layer:
        overload:
          global_downstream_max_connections: 50000

static_resources:
  listeners:
    - name: http_listener
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 8081

      # Connection Draining on Listener Removal
      drain_type: MODIFY_ONLY

      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http

                # Graceful Drain Settings
                drain_timeout: 30s
                delayed_close_timeout: 10s

                access_log:
                  - name: envoy.access_loggers.file
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
                      path: /var/log/envoy/access.log

                route_config:
                  name: main_route
                  virtual_hosts:
                    - name: ui_service
                      domains: ["shubhamsinghrajput.com"]
                      routes:
                        - match: {prefix: "/"}
                          route:
                            cluster: ui_cluster
                            timeout: 60s

                    - name: user_service
                      domains: ["users.shubhamsinghrajput.com"]
                      routes:
                        - match: {prefix: "/"}
                          route:
                            cluster: user_service_cluster
                            timeout: 30s

                    - name: shikshaspace_service
                      domains: ["shikshaspace.shubhamsinghrajput.com"]
                      routes:
                        - match: {prefix: "/"}
                          route:
                            cluster: shikshaspace_service_cluster
                            timeout: 30s

                    - name: keycloak
                      domains: ["keycloak.shubhamsinghrajput.com"]
                      routes:
                        - match: {prefix: "/"}
                          route:
                            cluster: keycloak_cluster
                            timeout: 60s

                http_filters:
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

  clusters:
    # UI Cluster - Load balance Blue/Green
    - name: ui_cluster
      connect_timeout: 5s
      type: STRICT_DNS
      lb_policy: ROUND_ROBIN
      health_checks:
        - timeout: 5s
          interval: 10s
          unhealthy_threshold: 2
          healthy_threshold: 2
          http_health_check:
            path: /actuator/health/readiness
      load_assignment:
        cluster_name: ui_cluster
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: localhost
                      port_value: 7500
              - endpoint:
                  address:
                    socket_address:
                      address: localhost
                      port_value: 7510

    # User Service - Load balance Blue/Green
    - name: user_service_cluster
      connect_timeout: 5s
      type: STRICT_DNS
      lb_policy: ROUND_ROBIN
      health_checks:
        - timeout: 5s
          interval: 10s
          unhealthy_threshold: 2
          healthy_threshold: 2
          http_health_check:
            path: /actuator/health/readiness
      load_assignment:
        cluster_name: user_service_cluster
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: localhost
                      port_value: 7501
              - endpoint:
                  address:
                    socket_address:
                      address: localhost
                      port_value: 7511

    # ShikshaSpace Service - Load balance Blue/Green
    - name: shikshaspace_service_cluster
      connect_timeout: 5s
      type: STRICT_DNS
      lb_policy: ROUND_ROBIN
      health_checks:
        - timeout: 5s
          interval: 10s
          unhealthy_threshold: 2
          healthy_threshold: 2
          http_health_check:
            path: /actuator/health/readiness
      load_assignment:
        cluster_name: shikshaspace_service_cluster
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: localhost
                      port_value: 7502
              - endpoint:
                  address:
                    socket_address:
                      address: localhost
                      port_value: 7512

    # Keycloak
    - name: keycloak_cluster
      connect_timeout: 5s
      type: STRICT_DNS
      lb_policy: ROUND_ROBIN
      health_checks:
        - timeout: 5s
          interval: 15s
          unhealthy_threshold: 3
          healthy_threshold: 2
          http_health_check:
            path: /health
      load_assignment:
        cluster_name: keycloak_cluster
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: localhost
                      port_value: 8080
