# Default values for microservice.
serviceName: ""
namespace: ""
replicaCount: 1

image:
  repository: ""
  tag: ""
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 9999

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
